"""empty message

Revision ID: 07ffd7abe22e
Revises: 2e816de2015e
Create Date: 2022-08-16 02:51:43.182182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ffd7abe22e'
down_revision = '2e816de2015e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.Column('Artist_id', sa.Integer(), nullable=False),
    sa.Column('Venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('looking_for_venues', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'date_updated')
    op.drop_column('Venue', 'date_created')
    op.drop_column('Venue', 'looking_for_venues')
    op.drop_column('Venue', 'website_link')
    op.drop_table('shows')
    # ### end Alembic commands ###
