"""empty message

Revision ID: 2e816de2015e
Revises: aaa42559bce0
Create Date: 2022-08-15 19:39:57.576338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e816de2015e'
down_revision = 'aaa42559bce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('looking_for_venues', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('Artist', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'date_updated')
    op.drop_column('Artist', 'date_created')
    op.drop_column('Artist', 'looking_for_venues')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
