"""empty message

Revision ID: ae533007c2de
Revises: 07ffd7abe22e
Create Date: 2022-08-20 17:15:26.347215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae533007c2de'
down_revision = '07ffd7abe22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('Venue', 'looking_for_venues')
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'venue_name')
    op.add_column('Venue', sa.Column('looking_for_venues', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
